### PR TITLE
Add i-gelb as featured sponsor

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

Forgot to do branch on repo.  This replaces https://github.com/ddev/ddev.com-front-end/pull/81

Add new major sponsor i-gelb as major in featured sponsors

Question/problem: I don't know how to get a square version of this, unless it's just taking the logo part on the right.

### CODE REVIEW

**Comment by mattstein** [comment]
You might swap in these:

Screen Shot 2023-08-15 at 08 59 02 AM@2x

- Removes white rectangle from the full version so it’s fully transparent.
- Adds a square variant that at least matches the site’s favicon in lieu of a brand guide—and looks more appropriate on the “Support DDEV” page.
- Runs both through ImageOptim to strip out cruft and reduce file weight.

i-gelb
i-gelb-square

**Comment by rfay** [comment]
Done, thanks. Not sure how you did all that and how you did it so fast.

**Comment by mattstein** [comment]
Magic!* ✨ 

_\*: Figma + [ImageOptim](https://imageoptim.com/mac)._

**Comment by rfay** [comment]
Thanks, up there.

**Review by mattstein — APPROVED** [review]

**Pull request merged**
