### PR TITLE
Fetch and merge `ddev` organization sponsors

### PR DESCRIPTION
**Pull request by mattstein**
## Issue

Now that DDEV has an [organization-level GitHub sponsorship](https://github.com/ddev/ddev/issues/4748) program, we’ll want to automatically include those sponsors on ddev.com, in addition to those already sponsoring `rfay`.

These are displayed on the [landing](https://ddev.com/#supporters) and [support](https://ddev.com/support-ddev/) pages:

landing-sponsors
support-sponsors

## What This PR Does

This adds to the existing GraphQL query to also grab sponsors for the `ddev` organization, and merges both sets of results (`rfay` sponsors and `ddev` sponsors).

It also updates the sponsorship CTA to point to the DDEV GitHub organization instead of Randy’s account.

### CODE REVIEW

**Comment by mattstein** [comment]
@rfay This should work in theory, but we’ll need at least one DDEV organization sponsor to know for sure. Leaving this here as a draft for now.

**Comment by rfay** [comment]
I expect to announce the change today, so we should be able to get some people in there after a while.

**Comment by rfay** [comment]
We now have a sponsor on the ddev org.

**Comment by mattstein** [comment]
Wonderful! This sponsor gets pulled in as expected testing locally—also visible [in this fresh build](https://74ab337d.ddev-com-front-end.pages.dev).

Merging now. 🎉

**Pull request merged**
